repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: rust-fmt
        name: rust-fmt
        language: system
        files: '\.rs$'
        entry: cd platform && cargo fmt -- --check

      # TODO: enable this once it can just check formatting without overwriting and directories are supported.
      # - id: roc-fmt
      #   name: roc-fmt
      #   language: system
      #   files: '\.roc$'
      #   entry: ./roc/target/release/roc format apps

      - id: rust-clippy
        name: rust-clippy
        language: system
        files: '\.rs$'
        entry: cd platform && cargo clippy -- -Dwarnings
        pass_filenames: false
